spring:
  application:
    name: product-services
  datasource:
    url: jdbc:postgresql://172.21.208.1:5432/productdb
    username: postgres
    password: as
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: products
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: products
    show-sql: true
  flyway:
    schemas: products
    enabled: true
